openapi: 3.0.3
info:
  title: une API simple de Ping
  version: 1.0.0
paths:
  /ping:
    get:
      description: ok
      responses:
        200:
          description: succualy !!
          content:
            text/plain:
              schema:
                example:
                  type: string
                  example: pong




