openapi: 3.0.3
info:
  title: Manipulation des paramètre et les réponses
  description: introduire les paramètres et les schéma JSON
  version: 1.0.0

servers:
  - url: http://localhost:8080


paths:
  /users:
    get:
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            example: 1
        - name: size
          in: query
          required: true
          schema:
            type: integer
            example: 20
      responses:
        "200":
          description: Liste des utilisateurs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "Alice"
                    email:
                      type: string
                      example: "alice@example.com"
        "400":
          description: Mauvais types de paramètres
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Bad types for provided query parameters"










